#!/usr/bin/env sh

docker_run_withX11 -it --rm \
-v vc_date_site:/dateSite \
-v vc_date_db:/var/lib/mysql \
-v vc_amore_site:/amoreSite \
-v vc_daq_fxs:/daqfxs \
-v vc_home_daq:/home/daq \
-v vc_amore_cdb:/local/cdb \
-v $(pwd):/localdrive \
--net ${DOCKER_ALICEONLINE_PROJECTNAME}_default \
alice-amore \
/opt/root/bin/root.exe
