#!/usr/bin/env sh
#
# create an amore container
# with the proper links etc...
# that can be used for the amore (modules) binaries
#

ali_start

host_name=${1:-ali-amore-default-hostname}
cmd=${2:-/bin/bash}
tty=""
if [ $# -gt 2 ]; then
    tty="t"
fi
docker_run_withX11 -i$tty --rm \
-v vc_date_site:/dateSite \
-v vc_date_db:/var/lib/mysql \
-v vc_amore_site:/amoreSite \
-v vc_daq_fxs:/daqfxs \
-v vc_home_daq:/home/daq \
-v vc_amore_cdb:/local/cdb \
--net ${DOCKER_ALICEONLINE_PROJECTNAME}_default \
--name=$host_name \
--hostname=$host_name \
alice-amore \
$cmd

exit $?

