version: '2'

services:
  datedb:
    image: mysql:5.6
    volumes:
      - vc_date_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: date 

  dim:
    build: date
    image: alice-date 
    volumes:
      - vc_date_site:/dateSite
    hostname:
      dim
    links:
      - datedb
    entrypoint: /dim_setup.sh

  infologger:
    build: date
    image: alice-date
    volumes:
      - vc_date_site:/dateSite
    links:
      - datedb
      - dim
    entrypoint: /infologger_setup.sh

  daqfxs:
    build: date 
    image: alice-date
    volumes:
      - vc_date_site:/dateSite
      - vc_daq_fxs:/daqfxs
      - vc_ssh_daqfxs:/etc/ssh:ro
      - vc_home_daq:/home/daq
    links:
      - dim
      - datedb
      - infologger
    hostname: daqfxs
    entrypoint: /usr/sbin/sshd -D
    
  agentrunner:
    build: amore
    image: alice-amore 
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - vc_ssh_agentrunner:/etc/ssh:ro
      - vc_home_dqm:/home/dqm
      - vc_home_daq:/home/daq
    links:
      - dim
      - datedb
      - infologger
    hostname: agentrunner
    entrypoint: /sshd_setup.sh

  dadev:
    build: online-devel
    image: alice-online-devel
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - vc_home_dqm:/home/dqm
      - vc_home_daq:/home/daq
    links:
      - dim
      - datedb
      - infologger
    hostname: dadev 
    entrypoint: /sshd_setup.sh

  archiver:
    build: amore
    image: alice-amore
    volumes:
      - vc_date_site:/dateSite
      - vc_amore_site:/amoreSite
    links:
      - dim
      - datedb
      - infologger
    hostname: archiver
    entrypoint: /archiver_setup.sh

  agentMCHExpert:
    build: amore
    image: alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
    links:
      - dim
      - datedb
      - infologger
      - agentFeeder
    hostname: runner-mchexpert
    environment: 
      DATE_RUN_NUMBER: 256289
      TZ: "Europe/Paris"
      DATA_SOURCE: /amoreSite/16000256289037.8802.raw 
    entrypoint: /agent_setup.sh -a MCHExpert -r
    cpu_shares: 256 

  agentFeeder:
    build: amore
    image: alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - /alice/data:/alice/data
      - ${DOCKER_ALICEONLINE_SRC}/filelist.txt:/filelist.txt
    links:
      - dim
      - datedb
      - infologger
    hostname: agentFeeder
    environment: 
      TZ: "Europe/Paris"
      COLLECTION: "/filelist.txt"
      DEROOT_PORT: 1234
    entrypoint: /feeder_setup.sh 
    cpu_shares: 256 

  agentMCHQAshifter:
    build: amore
    image: alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - /alice/data:/alice/data
      - ${DOCKER_ALICEONLINE_SRC}/filelist.txt:/filelist.txt
    links:
      - dim
      - datedb
      - infologger
      - agentFeeder
    hostname: runner-mchqashifter
    environment: 
      DATE_RUN_NUMBER: 256289
      TZ: "Europe/Paris"
      DEROOT_HOST: agentFeeder
      DEROOT_PORT: 1234
      #DEROOT_INPUT: collection:///filelist.txt
      #DATA_SOURCE: /alice/data/2017/LHC17a_MUON_TRK/000268552/raw/17000268552001.511.raw
      #DATA_SOURCE: /amoreSite/16000256289037.8802.raw
      DATA_SOURCE: /alice/data/2016/LHC16j/000256289/raw/16000256289037.8802.raw
    entrypoint: /agent_setup.sh -a MCHQAshifter -r
    cpu_shares: 256 

  amore-web:
    build: amore
    image: alice-amore 
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
        #- ~/alicesw/run2/amore-web:/opt/amore/web
      - vc_home_daq:/home/daq
      - vc_home_dqm:/home/dqm
    links:
      - dim
      - datedb
      - infologger
    ports:
      - 8100:80
    environment:
      DIM_DNS_NODE: "dim"
    entrypoint: /httpd_setup.sh
    cpu_shares: 256 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.3-1
    links:
      - datedb 
    ports:
      - 8080:80
    environment:
      PMA_HOST: datedb 

volumes:
  vc_amore_site_dev:
    external: true
  vc_amore_site:
    external: true
  vc_date_site:
    external: true
  vc_date_db:
    external: true
  vc_amore_cdb:
    external: true
  vc_daq_fxs:
    external: true
  vc_home_daq:
    external: true
  vc_home_dqm:
    external: true
  vc_ssh_daqfxs:
    external: true
  vc_ssh_agentrunner:
    external: true
