version: '2'

services:
  datedb:
    image: mysql:5.6
    volumes:
      - vc_date_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: date 

  dim:
    build: dim
    #image: alice-dim
    volumes:
      - vc_date_site:/dateSite
    hostname:
      dim
    links:
      - datedb

  infologger:
    build: infologger
    #image: alice-infologger
    volumes:
      - vc_date_site:/dateSite
    links:
      - datedb
      - dim

  agentTST:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
    links:
      - dim
      - datedb
      - infologger
    entrypoint: /amore_setup.sh amoreAgent -a TST01 -s /amoreSite/sorted.254646.raw -r
    cpu_shares: 256 

  agentMCH:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
    links:
      - dim
      - datedb
      - infologger
    entrypoint: /amore_setup.sh amoreAgent -a MCHQAShifter -s /amoreSite/sorted.254646.raw -r
    cpu_shares: 256 

  amore-web:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
    links:
      - dim
      - datedb
      - infologger
    ports:
      - 8100:80
    entrypoint: /amore_setup.sh httpd -DFOREGROUND 
    cpu_shares: 256 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - datedb 
    ports:
      - 8080:80
    environment:
      PMA_HOST: datedb 

volumes:
  vc_amore_site:
    external: true
  vc_date_site:
    external: true
  vc_date_db:
    external: true
