version: '2'

services:
  datedb:
    image: mysql:5.6
    volumes:
      - vc_date_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: date 

  dim:
    build: dim
    #image: alice-dim
    volumes:
      - vc_date_site:/dateSite
    hostname:
      dim
    links:
      - datedb

  infologger:
    build: infologger
    #image: alice-infologger
    volumes:
      - vc_date_site:/dateSite
    links:
      - datedb
      - dim

  das:
    build: da
    image: aphecetche/alice-muon-das

  agentTST:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
    links:
      - dim
      - datedb
      - infologger
    hostname: agentTST
    entrypoint: /amore_setup.sh amoreAgent -a TST01 -s /amoreSite/sorted.254646.raw -r
    cpu_shares: 256 

  daqfxs:
    image: aphecetche/alice-amore
    volumes:
      - vc_date_site:/dateSite
    links:
      - dim
      - datedb
      - infologger
    hostname: daqfxs
    entrypoint: /ssh_setup.sh
    volumes:
      - vc_daq_fxs:/daqfxs
    
  agentMCHQAShifter:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
    links:
      - dim
      - datedb
      - infologger
    hostname: agentMCHQAShifter
    entrypoint: /amore_setup.sh amoreAgent -a MCHQAShifter -s /amoreSite/15000237401023.509.FILTER_RAWMUON_WITH_ALIPHYSICS_v5-06-04-01.raw -r
    cpu_shares: 256 

  amore-web:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - ~/alicesw/run2/amore-web:/opt/amore/web
    links:
      - dim
      - datedb
      - infologger
    ports:
      - 8100:80
    environment:
      DIM_DNS_NODE: "dim"
    entrypoint: /amore_setup.sh httpd -DFOREGROUND 
    cpu_shares: 256 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - datedb 
    ports:
      - 8080:80
    environment:
      PMA_HOST: datedb 

volumes:
  vc_amore_site:
    external: true
  vc_date_site:
    external: true
  vc_date_db:
    external: true
  vc_amore_cdb:
    external: true
  vc_daq_fxs:
    external: true
