version: '2'

services:
  datedb:
    image: mysql:5.6
    volumes:
      - vc_date_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: date 

  dim:
    build: date
    image: alice-date 
    volumes:
      - vc_date_site:/dateSite
    hostname:
      dim
    links:
      - datedb
    entrypoint: /dim_setup.sh

  infologger:
    build: date
    image: alice-date
    volumes:
      - vc_date_site:/dateSite
    links:
      - datedb
      - dim
    entrypoint: /infologger_setup.sh

  daqfxs:
    build: date 
    image: alice-date
    volumes:
      - vc_date_site:/dateSite
      - vc_daq_fxs:/daqfxs
      - vc_ssh_daqfxs:/etc/ssh:ro
      - vc_home_daq:/home/daq
    links:
      - dim
      - datedb
      - infologger
    hostname: daqfxs
    entrypoint: /usr/sbin/sshd -D
    
  agentrunner:
    build: amore
    image: alice-amore 
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - vc_ssh_agentrunner:/etc/ssh:ro
      - vc_home_dqm:/home/dqm
      - vc_home_daq:/home/daq
    links:
      - dim
      - datedb
      - infologger
    hostname: agentrunner
    entrypoint: /amore_setup.sh /usr/sbin/sshd -D 

  dadev:
    build: online-devel
    image: alice-online-devel
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - vc_home_dqm:/home/dqm
      - vc_home_daq:/home/daq
    links:
      - dim
      - datedb
      - infologger
    hostname: dadev 
    entrypoint: /amore_setup.sh /usr/sbin/sshd -D 

  archiver:
    build: amore
    image: alice-amore
    volumes:
      - vc_date_site:/dateSite
      - vc_amore_site:/amoreSite
    links:
      - dim
      - datedb
      - infologger
    hostname: archiver
    entrypoint: /amore_setup.sh amoreArchiver -g db:amoreArchiverConfig.txt

  agentMCHQAshifter:
    build: amore
    image: alice-amore
    volumes:
      - vc_amore_site_dev:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - /etc/localtime:/etc/localtime
    links:
      - dim
      - datedb
      - infologger
    hostname: agentMCHQAshifter
#    entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/15000237401023.509.FILTER_RAWMUON_WITH_ALIPHYSICS_v5-06-04-01.raw -r
    environment: 
      DATE_RUN_NUMBER: 256289
      TZ: "Europe/Paris"
      #   entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/16000256289037.8802.raw -r -e 470 -c 1
    entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/16000256289037.8802.raw -r
    cpu_shares: 256 

#   agentMCHDA:
#     build: amore
#     image: alice-amore
#     volumes:
#       - vc_amore_site:/amoreSite
#       - vc_date_site:/dateSite
#       - vc_amore_cdb:/local/cdb
#       - /etc/localtime:/etc/localtime 
#     links:
#       - dim
#       - datedb
#       - infologger
#     hostname: agentMCHDA
#     environment: 
#       DATE_RUN_NUMBER: 256289
#       TZ: "Europe/Paris"
#     entrypoint: /amore_setup.sh amoreAgent -a MCHDA -s /data_for_db_agents.raw -r -t 45 
#     cpu_shares: 256 
# #
#   agentMCHQC:
#     build: amore
#     image: alice-amore
#     volumes:
#       - vc_amore_site:/amoreSite
#       - vc_date_site:/dateSite
#       - vc_amore_cdb:/local/cdb
#       - /etc/localtime:/etc/localtime 
#     links:
#       - dim
#       - datedb
#       - infologger
#     hostname: agentMCHQC
# #    entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/15000237401023.509.FILTER_RAWMUON_WITH_ALIPHYSICS_v5-06-04-01.raw -r
#     environment: 
#       DATE_RUN_NUMBER: 256289
#       TZ: "Europe/Paris"
#     entrypoint: /amore_setup.sh amoreAgent -a MCHQC -s /amoreSite/16000256289037.8802.raw -r -e 470 -c 1
#     #entrypoint: /amore_setup.sh amoreAgent -a MCHQC -s /amoreSite/16000256289037.8802.raw -r
#     cpu_shares: 256 
#
  amore-web:
    build: amore
    image: alice-amore 
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
        #- ~/alicesw/run2/amore-web:/opt/amore/web
      - vc_home_daq:/home/daq
      - vc_home_dqm:/home/dqm
    links:
      - dim
      - datedb
      - infologger
    ports:
      - 8100:80
    environment:
      DIM_DNS_NODE: "dim"
    entrypoint: /amore_setup.sh httpd -DFOREGROUND 
    cpu_shares: 256 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.3-1
    links:
      - datedb 
    ports:
      - 8080:80
    environment:
      PMA_HOST: datedb 

volumes:
  vc_amore_site_dev:
    external: true
  vc_amore_site:
    external: true
  vc_date_site:
    external: true
  vc_date_db:
    external: true
  vc_amore_cdb:
    external: true
  vc_daq_fxs:
    external: true
  vc_home_daq:
    external: true
  vc_home_dqm:
    external: true
  vc_ssh_daqfxs:
    external: true
  vc_ssh_agentrunner:
    external: true
