version: '2'

services:
  datedb:
    image: mysql:5.6
    volumes:
      - vc_date_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: date 

  dim:
    build: dim
    volumes:
      - vc_date_site:/dateSite
    hostname:
      dim
    links:
      - datedb

  infologger:
    build: infologger
    volumes:
      - vc_date_site:/dateSite
    links:
      - datedb
      - dim

  daqfxs:
    image: aphecetche/alice-amore
    volumes:
      - vc_date_site:/dateSite
      - vc_daq_fxs:/daqfxs
      - $PWD/ssh-server.daqfxs/:/etc/ssh:ro
      - $PWD/ssh-user.daq/:/home/daq/.ssh
    links:
      - dim
      - datedb
      - infologger
    hostname: daqfxs
    entrypoint: /usr/sbin/sshd -D
    
  agentrunner:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
      - $PWD/ssh-server.daqfxs/:/etc/ssh:ro
      - $PWD/ssh-user.daq/:/home/daq/.ssh
    links:
      - dim
      - datedb
      - infologger
    hostname: agentrunner
    entrypoint: /amore_setup.sh /usr/sbin/sshd -D 

  archiver:
    image: aphecetche/alice-amore
    volumes:
      - vc_date_site:/dateSite
      - vc_amore_site:/amoreSite
    links:
      - dim
      - datedb
      - infologger
    hostname: archiver
    entrypoint: /amore_setup.sh amoreArchiver -g db:amoreArchiverConfig.txt

  agentMCHQAshifter:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
    links:
      - dim
      - datedb
      - infologger
    hostname: agentMCHQAshifter
#    entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/15000237401023.509.FILTER_RAWMUON_WITH_ALIPHYSICS_v5-06-04-01.raw -r
    environment: 
      DATE_RUN_NUMBER: 256289
    # entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/16000256289037.8802.raw -r -e 1000 -c 1
    entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/16000256289037.8802.raw -r
    cpu_shares: 256 

  agentMCHQC:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - vc_amore_cdb:/local/cdb
    links:
      - dim
      - datedb
      - infologger
    hostname: agentMCHQC
#    entrypoint: /amore_setup.sh amoreAgent -a MCHQAshifter -s /amoreSite/15000237401023.509.FILTER_RAWMUON_WITH_ALIPHYSICS_v5-06-04-01.raw -r
    environment: 
      DATE_RUN_NUMBER: 256289
    #entrypoint: /amore_setup.sh amoreAgent -a MCHQC -s /amoreSite/16000256289037.8802.raw -r -e 1000 -c 1
    entrypoint: /amore_setup.sh amoreAgent -a MCHQC -s /amoreSite/16000256289037.8802.raw -r
    cpu_shares: 256 

  amore-web:
    image: aphecetche/alice-amore
    volumes:
      - vc_amore_site:/amoreSite
      - vc_date_site:/dateSite
      - ~/alicesw/run2/amore-web:/opt/amore/web
      - $PWD/ssh-user.daq/:/home/daq/.ssh
      - $PWD/ssh-user.daq/:/root/.ssh
    links:
      - dim
      - datedb
      - infologger
    ports:
      - 8100:80
    environment:
      DIM_DNS_NODE: "dim"
    entrypoint: /amore_setup.sh httpd -DFOREGROUND 
    cpu_shares: 256 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - datedb 
    ports:
      - 8080:80
    environment:
      PMA_HOST: datedb 

volumes:
  vc_amore_site:
    external: true
  vc_date_site:
    external: true
  vc_date_db:
    external: true
  vc_amore_cdb:
    external: true
  vc_daq_fxs:
    external: true
