# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# use decently recent dev tools
source scl_source enable git19 python27
pip install --upgrade alibuild==1.4.0.rc1

# start at /alicesw if available
if [[ -d /alicesw ]]; then
    cd /alicesw
    eval $(alienv load VO_ALICE@${ALI_WHAT}::latest-${ALI_VERSION}-daq)
    aliBuild analytics on
fi


